### ISSUE TITLE
change the description of the lib

### ISSUE THREAD

**Issue by bpetetot** [alakarteio/hoc-little-router#10]
> "HOC to hide a component when the route didn't match."

This is right but I think not the right way to describe it, it would be better to describe it like that : 

> "HOC for react and redux-little-router to render a component when the route is matching"

(it's also in the README.md file)

**Comment by fabienjuif** [comment]
What about  ?
1. `redux-little-router HOC to render a component when the route matches.`
2. `redux-little-router HOC to render a component when the route is matching!`

**Comment by hgwood** [comment]
Both are fine.
