### ISSUE TITLE
Manage Page Not Found through hoc

### ISSUE THREAD

**Issue by bpetetot** [alakarteio/hoc-little-router#3]
Display a "page not found" component when router can't match any `title` prop in routing configuration tree :

Example :
```es6
forRoute('HOME', { notFound: Page404 })(App)
```

**Comment by guillaumecrespel** [comment]
I think we have only one not found page.
if we define a default TITLE route for error page and not found page on list of routes ?

`export const { reducer, enhancer, middleware } = routerForBrowser({
  routes: {
    '/': { title: 'HOME',
      '/500': { title: '500' },
      '/404': { title: '404' },
    },
  },
  basename,
})`

And `forRoute('HOME', { 404: 'CUSTOM_404', 500: 'CUSTOM_500' })(App)` to extends default usage ?

**Comment by fabienjuif** [comment]
We speak about this solution with @bpetetot .
What does allow the `{ notFound: Page404 }` is to have multiple "not found" pages depending where you are on the graph: 
```
/
  - contacts/
     - Page404Contacts
  - cities/
     - Page404Cities
```

With your solution @guillaumecrespel, we only have one 404 page in the whole application since title are uniq.

**Comment by bpetetot** [comment]
This issue is more about the "**Route** Not Found" and not the "**404** not found" (the HTTP error due to a network request not found)

When a user types a route that doesn't exist, I want to display an error page and eventually different page, when the route is not found at different levels of the graph (as @fabienjuif said in the previous post)

**Comment by fabienjuif** [comment]
Yes you are write about the definition :)

**Comment by fabienjuif** [comment]
see #41
